update README.MD

diff --git a/.github/workflows/python-app.yml b/.github/workflows/python-app.yml
--- a/.github/workflows/python-app.yml
+++ b/.github/workflows/python-app.yml
@@ -5,8 +5,8 @@ on:
     branches: [ "deploy", "master" ]
 
 env:
-    AZURE_CONTAINER_REGISTRY: containerappimages11
-    CONTAINER_APP_NAME: containerapp11
+    AZURE_CONTAINER_REGISTRY: containerappimages
+    CONTAINER_APP_NAME: containerapp
     RESOURCE_GROUP: container
     LOCATION: eastus2
     PORT: 8501
@@ -24,39 +24,39 @@ jobs:
       with:
         python-version: "3.10"
     
-    # - name: Set up Docker Buildx
-    #   uses: docker/setup-buildx-action@v3
+    - name: Set up Docker Buildx
+      uses: docker/setup-buildx-action@v3
 
-    # - name: Validate build configuration (local test)
-    #   uses: docker/build-push-action@v6
-    #   with:
-    #       context: .
-    #       file: ./Dockerfile
-    #       call: check
+    - name: Validate build configuration (local test)
+      uses: docker/build-push-action@v6
+      with:
+          context: .
+          file: ./Dockerfile
+          call: check
 
-    # - name: Build Docker image (local test)
-    #   run: |
-    #       docker build -t containerapp:stage .
+    - name: Build Docker image (local test)
+      run: |
+          docker build -t containerapp:stage .
 
-    # - name: Run container (local test)
-    #   run: |
-    #       docker run -d -p 8501:8501 --name localtest containerapp:stage
-    #       sleep 10
+    - name: Run container (local test)
+      run: |
+          docker run -d -p 8501:8501 --name localtest containerapp:stage
+          sleep 10
 
-    # - name: Test app (local test)
-    #   run: |
-    #       status=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8501)
-    #       if [ "$status" -ne 200 ]; then
-    #           echo "Health check failed! Expected HTTP 200. Got $status"
-    #           exit 1
-    #       else
-    #           echo "Status $status"
-    #       fi
+    - name: Test app (local test)
+      run: |
+          status=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8501)
+          if [ "$status" -ne 200 ]; then
+              echo "Health check failed! Expected HTTP 200. Got $status"
+              exit 1
+          else
+              echo "Status $status"
+          fi
 
-    # - name: Clean container (local test)
-    #   run: |
-    #       docker stop localtest
-    #       docker rm localtest
+    - name: Clean container (local test)
+      run: |
+          docker stop localtest
+          docker rm localtest
 
     - name: Log in to Azure
       uses: azure/login@v2
@@ -119,6 +119,8 @@ jobs:
               az containerapp env create --name ${{ env.CONTAINER_APP_NAME }} --resource-group ${{ env.RESOURCE_GROUP }} --location ${{ env.LOCATION }}
           fi
 
+          echo "Creating the Container App..."
+
           az containerapp create \
               --name ${{ env.CONTAINER_APP_NAME }} \
               --resource-group ${{ env.RESOURCE_GROUP }} \
@@ -137,6 +139,10 @@ jobs:
               --query properties.configuration.ingress.fqdn \
               --output tsv
 
+            echo "Container App was created."
+
+            echo "Updating Role of Service Principal..."
+
             az role assignment create \
               --assignee $(az containerapp identity show \
                 --name ${{ env.CONTAINER_APP_NAME }} \
@@ -148,20 +154,15 @@ jobs:
                 --resource-group ${{ env.RESOURCE_GROUP }} \
                 --query id -o tsv)
 
+            echo "Updated Role."
+
+            echo "Updating Image of the Container App..."
+
             az containerapp update \
               --name ${{ env.CONTAINER_APP_NAME }} \
               --resource-group ${{ env.RESOURCE_GROUP }} \
               --image ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_APP_NAME }}:${{ github.sha }} \
               --output tsv
 
-    # - name: Deploy to Azure Container Apps
-    #   uses: azure/container-apps-deploy-action@v1
-    #   with:
-    #     imageToDeploy: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_APP_NAME }}:${{ github.sha }}
-    #     resourceGroup:  ${{ env.RESOURCE_GROUP }}
-    #     containerAppName: ${{ env.CONTAINER_APP_NAME }}
-    #     registryUrl: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io
-    #     registryUsername: ${{ secrets.AZURE_REGISTRY_USERNAME }}
-    #     registryPassword: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
-    #     environmentVariables: "DB_USER=${{ secrets.DB_USER }} DB_PORT=${{ secrets.DB_PORT }} DB_PASSWORD=${{ secrets.DB_PASSWORD }} DB_NAME=${{ secrets.DB_NAME }} DB_HOST=${{ secrets.DB_HOST }}"
+            echo "Updated Image."
               
